MVP TestNet with Java Docker API
yhassanzadeh13/lightchain-java pull request #18
Opened 2022-03-13 11:43 UTC by setrf

Includes the implementation of an HTTP Server, Prometheus and Grafana instances, which all run on a dedicated Docker Network within their respective containers. The setup and connections required are conducted entirely by the driver class utilizing Docker's Java API.

2022-03-14 14:07 UTC, thep2p requested changes
In addition to the following comments, please also update your PR description with a step-by-step guide on how one can see the results in `Prometheus` and `Grafana`, and what are the expected results. Thanks!

2022-03-14 14:07 UTC, thep2p commented on Dockerfile
> +COPY --from=build /app/target/lightchain-sdp-1.0-SNAPSHOT-jar-with-dependencies.jar .
When building the `jar` file, I can see that you hard-coded the `integration.localnet.DemoServer` as the `main` class. 

This means that the `main` class is tightly coupled with this demo server scenario, and changing it would be daunting. Especially down the road, we gonna have multiple main classes in different packages each serving a separate purpose. 


So, my proposition to fix this is as follows: 
1. To add a `build` tag to our existing `Makefile` which builds the entire project and creates `jar` file with `integration.localnet.DemoServer` as the `main` class. This should be the only place that we set `integration.localnet.DemoServer` as the `main` class, and we wipe `integration.localnet.DemoServer` from `src/main/resources/META-INF/MANIFEST.MF` and `pom.xml`.  So running `make build` will create a `jar` file of the project with `integration.localnet.DemoServer` as the `main` class and put it in `/app/target/lightchain-sdp-1.0-SNAPSHOT-jar-with-dependencies.jar`. 

2. To add a `testnet` tag to our existing `Makefile` which runs the `make build` and then this docker file. Hence, our other team members are only required to run `make testnet`, which re-builds a new jar file for them and runs the docker file for it accordingly.

*You may alternatively refactor this `Dockerfile` to serve the first solution (i.e., building with specific main class).

2022-03-14 14:07 UTC, thep2p commented on src/main/resources/META-INF/MANIFEST.MF
> +
As explained in an earlier comment, this should not be here, since it makes the project tightly coupled with `DemoServer` as the main class, which should not.

2022-03-14 14:07 UTC, thep2p commented on pom.xml
> +                        </archive>
As explained in an earlier comment, this should not be here, since it makes the project tightly coupled with `DemoServer` as the main class, which should not.

2022-03-14 20:19 UTC, setrf commented on pom.xml
> +                        </archive>
deleted at #https://github.com/yhassanzadeh13/lightchain-sdp/pull/18/commits/1f514647a0bbc5c55b8f5059850580154203d830 as requested

2022-03-14 20:20 UTC, setrf commented on src/main/resources/META-INF/MANIFEST.MF
> +
deleted at #https://github.com/yhassanzadeh13/lightchain-sdp/pull/18/commits/1f514647a0bbc5c55b8f5059850580154203d830 as requested

2022-03-14 20:21 UTC, setrf commented on Dockerfile
> +COPY --from=build /app/target/lightchain-sdp-1.0-SNAPSHOT-jar-with-dependencies.jar .
went for the Dockerfile alteration route and removed any other specific hard-coded references to DemoServer.main at @https://github.com/yhassanzadeh13/lightchain-sdp/pull/18/commits/1f514647a0bbc5c55b8f5059850580154203d830

2022-04-02 13:39 UTC, thep2p submitted a review, later dismissed
approved considering the major revisions I made.

2022-04-02 13:56 UTC, merged