Metric server for Prometheus and Grafana connection
yhassanzadeh13/lightchain-java pull request #5
Opened 2022-02-26 19:23 UTC by setrf

This particular implementation includes the initial HTTP based metric server for Prometheus' ability to export data from the application. 

prometheus yml file must be appended as to include:

targets: ["localhost:9090","localhost:8081"]

Afterwards, Grafana must be setup to use Prometheus at port 9090 as its data source. Then, the queries will include automatically the gauge and counter built-in to the server class and initiated via the Start() method. These metrics are respectfully, consensus_proposal_finalized_blocks_total and consensus_proposal_finalized_blocks_current.

2022-02-26 19:49 UTC, thep2p requested changes
Please apply my requested change, also please fix the `checkstyle` lint issues. You may run `make lint` on your `terminal` in IntelliJ and it points you to the lint issues you face. You may ignore `spotbugs` issues for now.

2022-02-26 19:49 UTC, thep2p commented on src/main/java/metrics/metricServer.java
> +                .name("consensus_proposal_current_block_count").help("Current block count").register();
This part should be done through using `LightChain`-defined interfaces, i.e., defining a `LightChainCollector` that implements the [`Collector` interface](https://github.com/yhassanzadeh13/lightchain-sdp/tree/master/src/main/java/metrics), instantiating a `lightchainCollector` instance, and then calling `finalizedBlockCount= lightchainCollector.counter().register(...)`, and `currentBlockCount= lightchainCollector.guage.register(....)`. Especifically, `register` method of `counter` and `guage` interfaces in your implementation should encapsulate the prometheus build logic, e.g., `return Gauge.build().name()..`

2022-02-27 04:46 UTC, thep2p commented on src/main/java/metrics/metricServer.java
> +        }
This entire file must only have this `main` function, and the `main` function must only have an instance of the `LightChainCollector` server, start it up, declare the `finalizedBlockCount` and `currentBlockCount` metrics, and increase them for sake of the demo. 

The rest of logic of the `server` must be encapsulated in the `metrics` [package](https://github.com/yhassanzadeh13/lightchain-sdp/tree/master/src/main/java/metrics) of `LightChain` as the `MetricsServer.java` accompanied with its `Start` and `Terminate` methods. Please be as Object-Oriented as possible.

2022-02-27 04:59 UTC, thep2p commented on src/main/java/metrics/metricServer.java
> +            e.printStackTrace();
Please handle the exceptions properly as [stated in this guideline](https://www.notion.so/Exception-Handling-Best-Practices-3884368564074ddc90321c1c19f91e69). In short, we should never print stack trace or ignore the exception in silence. Moreover, the `spotbugs` check will never pass on CI unless the exception is handled properly. 

The best practice implies that exceptions are **bubbled up to the main function with proper message appending**, i.e., here when `Start` faces an `IOException` it means the function execution has fallen into an _Illegal State_. Hence, instead of silently swallowing the exception through printing the stack trace, `Start` is expected to `throw` and `IllegalStateException` **by adding a proper message** to the `IOException`: 
`throw new IllegalStateException("could not start metrics server:\t" + e);`

But why an `IllegalStateException` and not just simply throwing the same `IOException e`? 
Because whoever is the caller of `Start` is not aware of its internals. Hence, an `IOException` will not help the caller of `Start` to understand what was wrong with it. Instead, throwing an `IllegalStateException` will signal that the execution of `Start` has stepped into an illegal state, and the "could not start metrics server" will help the caller understand what exactly was wrong. 

Note that whenever we `throw` an exception from a function, we **must** declare its specific type to the signature of the function, hence the `Start` would look like: `public void Start() throws IllegalStateException`. 

Please refactor accordingly.

2022-02-27 05:01 UTC, thep2p commented on src/main/java/metrics/metricServer.java
> +        currentBlockCount.inc(15);
Please note that this part is _example_ code. The _example_ code must never be mixed with the production code (i.e., the `Start` implementation). Please see my previous comment on how to refactor this properly.

2022-03-02 11:52 UTC, setrf commented on src/main/java/metrics/metricServer.java
> +                .name("consensus_proposal_current_block_count").help("Current block count").register();
fixed in #[8f3f82f](https://github.com/yhassanzadeh13/lightchain-sdp/pull/5/commits/8f3f82f303b5af9bdedf61fc9b636488b0e7c9e0)

2022-03-02 11:52 UTC, setrf commented on src/main/java/metrics/metricServer.java
> +        }
fixed in #[8f3f82f](https://github.com/yhassanzadeh13/lightchain-sdp/pull/5/commits/8f3f82f303b5af9bdedf61fc9b636488b0e7c9e0)

2022-03-02 11:52 UTC, setrf commented on src/main/java/metrics/metricServer.java
> +            e.printStackTrace();
fixed in #[bcab77e](https://github.com/yhassanzadeh13/lightchain-sdp/pull/5/commits/bcab77edec4ff881e7e3b7556135385a9ca7a99a)

2022-03-02 11:53 UTC, setrf commented on src/main/java/metrics/metricServer.java
> +        currentBlockCount.inc(15);
fixed in #[bcab77e](https://github.com/yhassanzadeh13/lightchain-sdp/pull/5/commits/bcab77edec4ff881e7e3b7556135385a9ca7a99a)

2022-03-05 21:51 UTC, saarantrass submitted a review, later dismissed

2022-03-08 14:43 UTC, thep2p commented on src/main/java/metrics/Demo.java
> +    MetricServer.start();
The exception is thrown but not handled here. This violates our [best practice on bubbling up exceptions](https://www.notion.so/Technical-Meetings-on-Mondays-0393130e28ee4fc584da5e431bd60c30#e2f045e1efc74bba90e5bf5facd81ca6).

2022-03-08 14:57 UTC, thep2p requested changes
In addition to the comments left, the PR must be self-sufficient, i.e., anyone without any specific knowledge of Prometheus and grafana could be able to replicate the same result without any external efforts and just by running the `Demo`. 

This is not the case for this PR. As you clearly mention, anyone needs an already up and running and well-configured Prometheus and Grafana to run this `Demo`, which violates the self-sufficiency of this PR. This could be easily resolved by for example running the `dockerprom` for Prometheus and Grafana as part of `main` methods lifecycle. 


> prometheus yml file must be appended as to include:
targets: ["localhost:9090","localhost:8081"]
Afterwards, Grafana must be setup to use Prometheus at port 9090 as its data source.

2022-03-08 14:57 UTC, thep2p commented on src/main/java/metrics/Demo.java
> +          "consensus", "proposal", "Finalized block count");
This part should be moved to `main` function since all these `register` methods are throwing an exception. **Any exception thrown must be handled properly based on our [exception handling guideline](https://www.notion.so/Exception-Handling-Best-Practices-3884368564074ddc90321c1c19f91e69)**.

2022-03-08 14:57 UTC, thep2p commented on src/main/java/metrics/LightChainCollector.java
> +  }
`LightChainCollector` must have an instance of the counter, gauge, and histogram as its own member fields and only return them when their relative methods are called. It must not initialize a new instance per invocation of methods.

2022-03-08 14:57 UTC, thep2p commented on src/main/java/metrics/LightChainCounter.java
> +    return Counter.build().name(namespace + "_" + subsystem + "_" + name).help(helpMessage).register();
⚠️ Incorrect: the counter builder already has `namespace` and `subsystem` methods. Those must not be squeezed into `name`.

2022-03-08 14:57 UTC, thep2p commented on src/main/java/metrics/LightChainGauge.java
> +    return Gauge.build().name(namespace + "_" + subsystem + "_" + name).help(helpMessage).register();
⚠️ Incorrect: the gauge builder already has `namespace` and `subsystem` methods. Those must not be squeezed into `name`.

2022-03-08 14:57 UTC, thep2p commented on src/main/java/metrics/LightChainHistogram.java
> +  }
⚠️ Incorrect: the histogram builder already has `namespace` and `subsystem` methods. Those must not be squeezed into `name`.

2022-03-08 14:57 UTC, thep2p commented on src/main/java/metrics/MetricServer.java
> +      server = new HTTPServer(8081);
the port number should be a `private static final` member of this class.

2022-03-08 14:57 UTC, thep2p commented on src/main/java/metrics/Demo.java
> +    currentBlockCount.inc(12);
Most probably just querying each metric once would not be enough to have an illustrative demo. You need an extensive number of queries (e.g., 1 per second).

2022-03-13 16:20 UTC, setrf commented on src/main/java/metrics/Demo.java
> +    MetricServer.start();
adressed in #https://github.com/yhassanzadeh13/lightchain-sdp/pull/5/commits/b72a67536bb85b88bb9ab1953e0140f8d87dc06a

2022-03-13 16:20 UTC, setrf commented on src/main/java/metrics/Demo.java
> +          "consensus", "proposal", "Finalized block count");
addressed in #https://github.com/yhassanzadeh13/lightchain-sdp/pull/5/commits/b72a67536bb85b88bb9ab1953e0140f8d87dc06a

2022-03-13 16:21 UTC, setrf commented on src/main/java/metrics/LightChainCollector.java
> +  }
fixed in #https://github.com/yhassanzadeh13/lightchain-sdp/pull/5/commits/b72a67536bb85b88bb9ab1953e0140f8d87dc06a

2022-03-13 16:21 UTC, setrf commented on src/main/java/metrics/LightChainCounter.java
> +    return Counter.build().name(namespace + "_" + subsystem + "_" + name).help(helpMessage).register();
fixed in #https://github.com/yhassanzadeh13/lightchain-sdp/pull/5/commits/b72a67536bb85b88bb9ab1953e0140f8d87dc06a

2022-03-13 16:21 UTC, setrf commented on src/main/java/metrics/LightChainGauge.java
> +    return Gauge.build().name(namespace + "_" + subsystem + "_" + name).help(helpMessage).register();
fixed in #https://github.com/yhassanzadeh13/lightchain-sdp/pull/5/commits/b72a67536bb85b88bb9ab1953e0140f8d87dc06a

2022-03-13 16:21 UTC, setrf commented on src/main/java/metrics/LightChainHistogram.java
> +  }
fixed in #https://github.com/yhassanzadeh13/lightchain-sdp/pull/5/commits/b72a67536bb85b88bb9ab1953e0140f8d87dc06a

2022-03-13 16:21 UTC, setrf commented on src/main/java/metrics/MetricServer.java
> +      server = new HTTPServer(8081);
fixed in #https://github.com/yhassanzadeh13/lightchain-sdp/pull/5/commits/b72a67536bb85b88bb9ab1953e0140f8d87dc06a

2022-03-13 16:21 UTC, setrf commented on src/main/java/metrics/Demo.java
> +    currentBlockCount.inc(12);
fixed in #https://github.com/yhassanzadeh13/lightchain-sdp/pull/5/commits/b72a67536bb85b88bb9ab1953e0140f8d87dc06a

2022-03-17 14:37 UTC, thep2p requested changes
There are still some issues with PR, please address all of the comments as meticulously as possible.
⚠️ ⚠️ ⚠️ This [critical]((https://github.com/yhassanzadeh13/lightchain-sdp/pull/5#pullrequestreview-903115366) comment has not been addressed.

⚠️  All comments on my second review have been addressed with the same commit https://github.com/yhassanzadeh13/lightchain-sdp/commit/b72a67536bb85b88bb9ab1953e0140f8d87dc06a which does not represent a viable solution to any of them.

2022-03-17 14:37 UTC, thep2p commented on src/main/java/metrics/LightChainCollector.java
> +  CounterCollector lightChainCounter = new LightChainCounter();
All non-static and non-final member fields of a class must be declared in its constructor. Moreover, please always refer to non-static member fields of a class by `this`.

2022-03-17 14:37 UTC, thep2p commented on src/main/java/metrics/LightChainCollector.java
> +  }
Please always refer to non-static member fields of a class by `this`, i.e., return `this.lightChainHistogram`.

2022-03-17 14:37 UTC, thep2p commented on src/main/java/metrics/LightChainCounter.java
> +
There should not be any empty lines between the java doc and the module it is representing. This happens in several places throught your PR, please fix them all.

2022-03-17 14:37 UTC, thep2p commented on src/main/java/metrics/LightChainCounter.java
> +    return Counter.build().namespace(namespace).subsystem(subsystem).name(name).help(helpMessage).register();
Typically, such nested object method invocations are split into multiple lines, please refactor it entirely. 
```
    return Counter
        .build()
        .namespace(namespace)
        .subsystem(subsystem)
        .name(name)
        .help(helpMessage)
        .register();
```

2022-03-17 14:37 UTC, thep2p commented on src/main/java/metrics/Demo.java
> +    }
⚠️  ⚠️  ⚠️ The way most of the exceptions handled in this PR is flawed and incorrect. I ask you please read this short [tutorial](https://www.notion.so/Exception-Handling-Best-Practices-3884368564074ddc90321c1c19f91e69) carefully and to the letter. 

[Catching the `Exception`](https://www.notion.so/Exception-Handling-Best-Practices-3884368564074ddc90321c1c19f91e69#db879cf350d9417582cc6f696140bed1) type is a blatant violation of our exception handling guideline. As it is clearly stated in the guideline, you must _only catch the exceptions that you expect to be thrown_. 

Moreover, when it comes to the body of the `catch`, you should be mindful of what you expect the code do when it faces an _expected_ exception? An exception being thrown means the _normal flow of the program_ cannot be continued due to a fault that Java is unable to handle. In this case, when Java is unable to register your metrics, what do you expect the code to do? do you expect it to just print an error and continue to the next line and start a metrics server? or you would expect the entire [program crash](https://www.notion.so/Exception-Handling-Best-Practices-3884368564074ddc90321c1c19f91e69)?

2022-03-17 14:37 UTC, thep2p commented on src/main/java/metrics/Demo.java
> +        Thread.currentThread().interrupt();
⚠️ ⚠️ ⚠️ Another example of unsafe exception handling, the code reaches here when the current thread has already been interrupted, and then you interrupt it once more, which may result in a more severe runtime error.

2022-03-19 10:29 UTC, setrf commented on src/main/java/metrics/LightChainCollector.java
> +  CounterCollector lightChainCounter = new LightChainCounter();
Fixed in #https://github.com/yhassanzadeh13/lightchain-sdp/pull/5/commits/19e8226b6a702f4363427d8b9eab17ff7beea659

2022-03-19 10:29 UTC, setrf commented on src/main/java/metrics/LightChainCollector.java
> +  }
Fixed in #https://github.com/yhassanzadeh13/lightchain-sdp/pull/5/commits/19e8226b6a702f4363427d8b9eab17ff7beea659

2022-03-19 10:29 UTC, setrf commented on src/main/java/metrics/LightChainCounter.java
> +
Addressed via #https://github.com/yhassanzadeh13/lightchain-sdp/pull/5/commits/19e8226b6a702f4363427d8b9eab17ff7beea659

2022-03-19 10:29 UTC, setrf commented on src/main/java/metrics/LightChainCounter.java
> +    return Counter.build().namespace(namespace).subsystem(subsystem).name(name).help(helpMessage).register();
Fixed in #https://github.com/yhassanzadeh13/lightchain-sdp/pull/5/commits/19e8226b6a702f4363427d8b9eab17ff7beea659

2022-03-19 10:39 UTC, setrf commented on src/main/java/metrics/Demo.java
> +    }
Thank you for the heads up. Fixed in #https://github.com/yhassanzadeh13/lightchain-sdp/pull/5/commits/1b1934c130a7205d7b8b2ac3756b682c01f88881 per your guidance.

2022-03-19 10:39 UTC, setrf commented on src/main/java/metrics/Demo.java
> +        Thread.currentThread().interrupt();
Fixed in #https://github.com/yhassanzadeh13/lightchain-sdp/pull/5/commits/1b1934c130a7205d7b8b2ac3756b682c01f88881 per your guidance.

2022-03-19 10:41 UTC, setrf commented on src/main/java/metrics/Demo.java
> +          "consensus", "proposal", "Finalized block count");
Following your advice, the Docker API was utilized in order to make the latest version of the PR completely self sufficient. Now all the end-user needs to do is to run `Demo`

Fixed in #https://github.com/yhassanzadeh13/lightchain-sdp/pull/5/commits/1b1934c130a7205d7b8b2ac3756b682c01f88881

2022-03-23 13:22 UTC, merged