Ozan/json encoder and sha3256 hashing
yhassanzadeh13/lightchain-java pull request #6
Opened 2022-02-28 16:41 UTC by onacitarhan17

Adds JSON encoder/decoder, SHA3-256 functionality and regarding tests

2022-02-28 18:54 UTC, onacitarhan17 commented
I'm aware of exception issues, will fix it.

2022-03-01 13:22 UTC, onacitarhan17 commented
handled exceptions properly in https://github.com/yhassanzadeh13/lightchain-sdp/pull/6/commits/383bcc514d40419f171c4ac72d2ba62492039944

2022-03-03 05:39 UTC, thep2p requested changes

2022-03-03 05:39 UTC, thep2p commented on src/main/java/crypto/Sha3256Hasher.java
> +    String algorithm = "SHA-256";
This must be a class-level static constant (i.e., `final`) named `HASH_ALG_SHA_3_256`. Also, I think the `MessageDigest` is stateless, hence it can be also a `private static` variable at the class level.

2022-03-03 05:39 UTC, thep2p commented on src/main/java/model/crypto/Sha3256Hash.java
> +  }
This two constructors should have sanity checks to make sure that whatever is passed as parameter is 32 bytes.

2022-03-03 05:39 UTC, thep2p commented on src/main/java/model/fixture/TestEntity.java
> +package model.fixture;
Everything we develop for testing must be in `src/test/java/..`. 

In very specific, this file should be placed in `src/test/java/unittest/fixtures/`. 

Please note that no residue of any test-level code should be in `src/main/java/,,,`

2022-03-03 05:39 UTC, thep2p commented on src/main/java/model/fixture/TestEntity.java
> +public class TestEntity extends Entity {
Please rename it as `EntityFixture` and combine it with an already implemented `EntityFixture` on `src/test/java/unittest/fixtures/EntityFixture.java`.

2022-03-03 05:39 UTC, thep2p commented on src/main/java/model/fixture/TestEntity.java
> +  private String testType;
Additionally, please include a byte array, a hash array (`Sha3256Hash[]`), and an array of identifiers as member fields.

2022-03-03 05:39 UTC, thep2p commented on src/main/java/model/fixture/TestEntity.java
> +  }
One should be able to create a _new_ `EntityFixture` every time it calls the _default constructor_. For this, the default constructor must include involving a `static final` random generator to fill in the member fields of the `EntityFixture` whenever it is called. Note that the random generator must be a `static final` member of this class, so that it holds its state across all `EntityFixture` objects created. 

Note that for bytes and identifiers you can use the fixtures that are already provided in `test/java/unittest/fixture/`

2022-03-03 05:39 UTC, thep2p commented on src/main/java/model/fixture/TestEntity.java
> +  }
As explained in the previous comment, except for the default constructor, an `EntityFixture` should not have any other constructor or setters. Please remove them.

2022-03-03 05:39 UTC, thep2p commented on src/main/java/modules/codec/JsonEncoder.java
> +      byte[] bytes = mapper.writeValueAsString(e).getBytes(StandardCharsets.UTF_8);
Does not look like a correct way of encoding our `Entity` objects. The mapper treats the `Entity e` as a class with _human readable_ values, and hence encodes them assuming they are representable with `UTF_8` codec. The issue is most of the `LightChain` entities are not going to be human-readable or encodable such coding assumptions. We need a general-purpose encoder that can encode almost anything into bytes without any specific assumption on what the data object encapsulates. The only legitimate assumption around encoding an entity must be its self-declared type through the `type()` method. 

I am guessing once you include non-`UTF_8` representations into an `EntityFixture`, the encoding and decoding are going to fail. For example, as explained on an earlier comment once you include `byte[]`, `Identifier[]`, or `Sha3256Hash[]` objects as _member fields_ of an `EntityFixture`, its encoding is failed at least in the sense that the decoder is no longer able to recover the encoded object. 

So please refactor the implementation by looking for a more general encoder functionality that does not make any such explicit assumption about data representation. A good example of such is [this tutorial](https://www.tutorialspoint.com/How-to-convert-an-object-to-byte-array-in-java) though, it relies on `Serializable` interface of Java and is not JSON-based. However, as shown there, no assumption is made around the object being encoded except that it is a Java object. This may inspire your investigation to find a more powerful JSON encoder that does not rely on any assumption about the object being encoded.

2022-03-03 05:39 UTC, thep2p commented on src/test/java/crypto/Sha3256HashTest.java
> +    public void Test1(){
Each test should have a [meaningful name reflecting what it is testing](https://dzone.com/articles/7-popular-unit-test-naming) as well as a [descriptive java doc](https://stackoverflow.com/questions/2968010/javadoc-in-junit-test-classes).

2022-03-03 05:39 UTC, thep2p commented on src/test/java/crypto/Sha3256HashTest.java
> +        Assertions.assertEquals(hash.compare(new Sha3256Hash(testHex.getBytes())), 0);
For all these tests, please create `hash1` and `hash2`. This way it is more readable to write `hash1.compare(hash2)`. 

Also, please add `public final static` constants for 0, 1, and -1 in `model.crypto.Hash` such as:
```
public static final int EQUAL = 0;
public static final int LESS = -1; 
public static final int GREATER = 1; 
```

Hence this tests will be refactored accordingly for example: 
`Assertions.assertEquals(hash1.compare(hash2, Hash.EQUAL)`;
which is significantly more readable.

2022-03-03 05:39 UTC, thep2p commented on src/test/java/crypto/Sha3256HasherTest.java
> +    }
Please refactor this test to run the hash in the loop and compare each hash value with the previous iteration. Same comment applies to the next test.

2022-03-03 05:39 UTC, thep2p commented on src/test/java/modules/JsonEncoderTest.java
> +    System.out.println("Entities are equal: " + entity.equals(entityChanged));
These types of tests are called `TestEncodingRoundTrip`. Please rename it. Also, please extend the test with the complete form of the `EntityFixture` including the bytes, hashes and identifiers as asked earlier.

2022-03-03 11:20 UTC, onacitarhan17 commented on src/main/java/model/crypto/Sha3256Hash.java
> +  }
fixed in https://github.com/yhassanzadeh13/lightchain-sdp/pull/6/commits/aff1cbd79d168bc0ec07871cc0410bb48278593d

2022-03-03 12:57 UTC, onacitarhan17 commented on src/test/java/modules/JsonEncoderTest.java
> +    System.out.println("Entities are equal: " + entity.equals(entityChanged));
fixed in https://github.com/yhassanzadeh13/lightchain-sdp/pull/6/commits/696ce81fce474acf2e4ae8134a69fa2f7d25c899

2022-03-03 12:57 UTC, onacitarhan17 commented on src/test/java/crypto/Sha3256HasherTest.java
> +    }
fixed in https://github.com/yhassanzadeh13/lightchain-sdp/pull/6/commits/696ce81fce474acf2e4ae8134a69fa2f7d25c899

2022-03-03 12:58 UTC, onacitarhan17 commented on src/test/java/crypto/Sha3256HashTest.java
> +        Assertions.assertEquals(hash.compare(new Sha3256Hash(testHex.getBytes())), 0);
fixed in https://github.com/yhassanzadeh13/lightchain-sdp/pull/6/commits/696ce81fce474acf2e4ae8134a69fa2f7d25c899

2022-03-03 13:00 UTC, onacitarhan17 commented on src/main/java/model/fixture/TestEntity.java
> +  private String testType;
fixed in https://github.com/yhassanzadeh13/lightchain-sdp/pull/6/commits/696ce81fce474acf2e4ae8134a69fa2f7d25c899

2022-03-03 13:00 UTC, onacitarhan17 commented on src/main/java/model/fixture/TestEntity.java
> +public class TestEntity extends Entity {
fixed in https://github.com/yhassanzadeh13/lightchain-sdp/pull/6/commits/696ce81fce474acf2e4ae8134a69fa2f7d25c899

2022-03-03 13:00 UTC, onacitarhan17 commented on src/main/java/model/fixture/TestEntity.java
> +package model.fixture;
fixed in https://github.com/yhassanzadeh13/lightchain-sdp/pull/6/commits/696ce81fce474acf2e4ae8134a69fa2f7d25c899

2022-03-03 13:00 UTC, onacitarhan17 commented on src/main/java/model/fixture/TestEntity.java
> +  }
fixed in https://github.com/yhassanzadeh13/lightchain-sdp/pull/6/commits/696ce81fce474acf2e4ae8134a69fa2f7d25c899

2022-03-03 13:02 UTC, onacitarhan17 commented on src/test/java/crypto/Sha3256HashTest.java
> +    public void Test1(){
fixed in https://github.com/yhassanzadeh13/lightchain-sdp/pull/6/commits/53a52b47428f4330207ca29f5402fd7b15f1684e

2022-03-03 14:56 UTC, onacitarhan17 commented on src/main/java/modules/codec/JsonEncoder.java
> +      byte[] bytes = mapper.writeValueAsString(e).getBytes(StandardCharsets.UTF_8);
fixed in https://github.com/yhassanzadeh13/lightchain-sdp/pull/6/commits/18c8378981332706790a2e030a47224a770653e0

2022-03-03 14:57 UTC, onacitarhan17 commented on src/main/java/model/fixture/TestEntity.java
> +  }
fixed in https://github.com/yhassanzadeh13/lightchain-sdp/pull/6/commits/18c8378981332706790a2e030a47224a770653e0

2022-03-03 15:11 UTC, onacitarhan17 commented on src/main/java/crypto/Sha3256Hasher.java
> +    String algorithm = "SHA-256";
fixed in https://github.com/yhassanzadeh13/lightchain-sdp/pull/6/commits/7fb2766534254ca8722b3d52cb41a33ef3218a96

2022-03-07 14:34 UTC, akucukoduk16 submitted a review, later dismissed

2022-03-07 16:05 UTC, thep2p reviewed
Thanks for applying the comments, just a few small hammerings and then we are good to go.

2022-03-07 16:05 UTC, thep2p commented on src/test/java/unittest/fixtures/EntityFixture.java
> +    this.testHashArray = new Sha3256Hash[32];
This field is never getting value. Please implement an `Sha3256HashFixture` in this package, and use that fixture to assign value to this.

2022-03-07 16:05 UTC, thep2p commented on src/test/java/unittest/fixtures/EntityFixture.java
> +    this.testBytes = bytesTest;
For this part, please use already provided [`Bytes.ByteArrayFixture`](https://github.com/yhassanzadeh13/lightchain-sdp/blob/master/src/test/java/unittest/fixtures/Bytes.java#L13)

2022-03-07 16:05 UTC, thep2p commented on src/test/java/unittest/fixtures/EntityFixture.java
>    }
Entity fixture must not have any setters.

2022-03-07 16:05 UTC, thep2p commented on src/test/java/unittest/fixtures/EntityFixture.java
> +  private Sha3256Hash[] testHashArray;
All fields of a entity fixture must be declared `final`.

2022-03-07 16:46 UTC, onacitarhan17 commented on src/test/java/unittest/fixtures/EntityFixture.java
> +  private Sha3256Hash[] testHashArray;
fixed in https://github.com/yhassanzadeh13/lightchain-sdp/pull/6/commits/2f624a9bc938fc528681f8a44e8c853941ab8117

2022-03-07 16:46 UTC, onacitarhan17 commented on src/test/java/unittest/fixtures/EntityFixture.java
>    }
fixed in https://github.com/yhassanzadeh13/lightchain-sdp/pull/6/commits/2f624a9bc938fc528681f8a44e8c853941ab8117

2022-03-07 16:46 UTC, onacitarhan17 commented on src/test/java/unittest/fixtures/EntityFixture.java
> +    this.testBytes = bytesTest;
fixed in https://github.com/yhassanzadeh13/lightchain-sdp/pull/6/commits/2f624a9bc938fc528681f8a44e8c853941ab8117

2022-03-07 16:46 UTC, onacitarhan17 commented on src/test/java/unittest/fixtures/EntityFixture.java
> +    this.testHashArray = new Sha3256Hash[32];
fixed in https://github.com/yhassanzadeh13/lightchain-sdp/pull/6/commits/2f624a9bc938fc528681f8a44e8c853941ab8117

2022-03-08 14:29 UTC, thep2p approved these changes
👏  shaped very well!

2022-03-08 14:29 UTC, merged